version: '3.8'

services:
  nyxsynth-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ${NYXSYNTH_CONFIG_DIR:-/etc/nyxsynth}:/etc/nyxsynth
      - ${NYXSYNTH_DATA_DIR:-/var/lib/nyxsynth}:/var/lib/nyxsynth
    ports:
      - "5000:5000"
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-nyxadmin123}
    restart: unless-stopped

  nyxsynth-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - nyxsynth-backend
    restart: unless-stopped
